<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['codigo' => 'AD', 'nome' => 'Andorra'],
            ['codigo' => 'AE', 'nome' => 'Emirados Árabes Unidos'],
            ['codigo' => 'AF', 'nome' => 'Afeganistão'],
            ['codigo' => 'AG', 'nome' => 'Antígua e Barbuda'],
            ['codigo' => 'AI', 'nome' => 'Anguilla'],
            ['codigo' => 'AL', 'nome' => 'Albânia, República da'],
            ['codigo' => 'AM', 'nome' => 'Armênia, República da'],
            ['codigo' => 'AO', 'nome' => 'Angola'],
            ['codigo' => 'AQ', 'nome' => 'Antártica'],
            ['codigo' => 'AR', 'nome' => 'Argentina'],
            ['codigo' => 'AS', 'nome' => 'Samoa Americana'],
            ['codigo' => 'AT', 'nome' => 'Áustria'],
            ['codigo' => 'AU', 'nome' => 'Austrália'],
            ['codigo' => 'AW', 'nome' => 'Aruba'],
            ['codigo' => 'AX', 'nome' => 'Aland, Ilhas'],
            ['codigo' => 'AZ', 'nome' => 'Azerbaijão, República do'],
            ['codigo' => 'BA', 'nome' => 'Bosnia-Herzegovina, República da'],
            ['codigo' => 'BB', 'nome' => 'Barbados'],
            ['codigo' => 'BD', 'nome' => 'Bangladesh'],
            ['codigo' => 'BE', 'nome' => 'Bélgica'],
            ['codigo' => 'BF', 'nome' => 'Burkina Faso'],
            ['codigo' => 'BG', 'nome' => 'Bulgária, República da'],
            ['codigo' => 'BH', 'nome' => 'Bahrein, Ilhas'],
            ['codigo' => 'BI', 'nome' => 'Burundi'],
            ['codigo' => 'BJ', 'nome' => 'Benim'],
            ['codigo' => 'BL', 'nome' => 'São Bartolomeu'],
            ['codigo' => 'BM', 'nome' => 'Bermudas'],
            ['codigo' => 'BN', 'nome' => 'Brunei'],
            ['codigo' => 'BO', 'nome' => 'Bolívia'],
            ['codigo' => 'BQ', 'nome' => 'Bonaire, Santo Eustáquio e Saba'],
            ['codigo' => 'BR', 'nome' => 'Brasil'],
            ['codigo' => 'BS', 'nome' => 'Bahamas, Ilhas'],
            ['codigo' => 'BT', 'nome' => 'Butão'],
            ['codigo' => 'BV', 'nome' => 'Bouvet, Ilha'],
            ['codigo' => 'BW', 'nome' => 'Botsuana'],
            ['codigo' => 'BY', 'nome' => 'Belarus, República da'],
            ['codigo' => 'BZ', 'nome' => 'Belize'],
            ['codigo' => 'CA', 'nome' => 'Canadá'],
            ['codigo' => 'CC', 'nome' => 'Cocos(Keeling), Ilhas'],
            ['codigo' => 'CD', 'nome' => 'Congo, República Democrática do'],
            ['codigo' => 'CF', 'nome' => 'República Centro-Africana'],
            ['codigo' => 'CG', 'nome' => 'Congo'],
            ['codigo' => 'CH', 'nome' => 'Suíça'],
            ['codigo' => 'CI', 'nome' => 'Costa do Marfim'],
            ['codigo' => 'CK', 'nome' => 'Cook, Ilhas'],
            ['codigo' => 'CL', 'nome' => 'Chile'],
            ['codigo' => 'CM', 'nome' => 'Camarões'],
            ['codigo' => 'CN', 'nome' => 'China, República Popular'],
            ['codigo' => 'CO', 'nome' => 'Colômbia'],
            ['codigo' => 'CR', 'nome' => 'Costa Rica'],
            ['codigo' => 'CU', 'nome' => 'Cuba'],
            ['codigo' => 'CV', 'nome' => 'Cabo Verde, República de'],
            ['codigo' => 'CW', 'nome' => 'Curaçao'],
            ['codigo' => 'CX', 'nome' => 'Christmas, Ilha'],
            ['codigo' => 'CY', 'nome' => 'Chipre'],
            ['codigo' => 'CZ', 'nome' => 'Tcheca, República'],
            ['codigo' => 'DE', 'nome' => 'Alemanha'],
            ['codigo' => 'DJ', 'nome' => 'Djibuti'],
            ['codigo' => 'DK', 'nome' => 'Dinamarca'],
            ['codigo' => 'DM', 'nome' => 'Dominica, Ilha'],
            ['codigo' => 'DO', 'nome' => 'República Dominicana'],
            ['codigo' => 'DZ', 'nome' => 'Argélia'],
            ['codigo' => 'EC', 'nome' => 'Equador'],
            ['codigo' => 'EE', 'nome' => 'Estônia, República da'],
            ['codigo' => 'EG', 'nome' => 'Egito'],
            ['codigo' => 'EH', 'nome' => 'Saara Ocidental'],
            ['codigo' => 'ER', 'nome' => 'Eritreia'],
            ['codigo' => 'ES', 'nome' => 'Espanha'],
            ['codigo' => 'ET', 'nome' => 'Etiópia'],
            ['codigo' => 'FI', 'nome' => 'Finlândia'],
            ['codigo' => 'FJ', 'nome' => 'Fiji'],
            ['codigo' => 'FK', 'nome' => 'Falkland (Ilhas Malvinas)'],
            ['codigo' => 'FM', 'nome' => 'Micronésia'],
            ['codigo' => 'FO', 'nome' => 'Feroe, Ilhas'],
            ['codigo' => 'FR', 'nome' => 'França'],
            ['codigo' => 'GA', 'nome' => 'Gabão'],
            ['codigo' => 'GB', 'nome' => 'Reino Unido'],
            ['codigo' => 'GD', 'nome' => 'Granada'],
            ['codigo' => 'GE', 'nome' => 'Geórgia, República da'],
            ['codigo' => 'GF', 'nome' => 'Guiana Francesa'],
            ['codigo' => 'GG', 'nome' => 'Guernsey'],
            ['codigo' => 'GH', 'nome' => 'Gana'],
            ['codigo' => 'GI', 'nome' => 'Gibraltar'],
            ['codigo' => 'GL', 'nome' => 'Groenlândia'],
            ['codigo' => 'GM', 'nome' => 'Gambia'],
            ['codigo' => 'GN', 'nome' => 'Guiné'],
            ['codigo' => 'GP', 'nome' => 'Guadalupe'],
            ['codigo' => 'GQ', 'nome' => 'Guiné-Equatorial'],
            ['codigo' => 'GR', 'nome' => 'Grécia'],
            ['codigo' => 'GS', 'nome' => 'Ilhas Geórgia do Sul e Sandwich do Sul'],
            ['codigo' => 'GT', 'nome' => 'Guatemala'],
            ['codigo' => 'GU', 'nome' => 'Guam'],
            ['codigo' => 'GW', 'nome' => 'Guiné-Bissau'],
            ['codigo' => 'GY', 'nome' => 'Guiana'],
            ['codigo' => 'HK', 'nome' => 'Hong Kong'],
            ['codigo' => 'HM', 'nome' => 'Ilha Heard e Ilhas McDonald'],
            ['codigo' => 'HN', 'nome' => 'Honduras'],
            ['codigo' => 'HR', 'nome' => 'Croácia, República da'],
            ['codigo' => 'HT', 'nome' => 'Haiti'],
            ['codigo' => 'HU', 'nome' => 'Hungria, República da'],
            ['codigo' => 'ID', 'nome' => 'Indonésia'],
            ['codigo' => 'IE', 'nome' => 'Irlanda'],
            ['codigo' => 'IL', 'nome' => 'Israel'],
            ['codigo' => 'IM', 'nome' => 'Man, Ilha de'],
            ['codigo' => 'IN', 'nome' => 'Índia'],
            ['codigo' => 'IO', 'nome' => 'Território Britânico no Oceano Índico'],
            ['codigo' => 'IQ', 'nome' => 'Iraque'],
            ['codigo' => 'IR', 'nome' => 'Irã, República Islâmica do'],
            ['codigo' => 'IS', 'nome' => 'Islândia'],
            ['codigo' => 'IT', 'nome' => 'Itália'],
            ['codigo' => 'JE', 'nome' => 'Jersey'],
            ['codigo' => 'JM', 'nome' => 'Jamaica'],
            ['codigo' => 'JO', 'nome' => 'Jordânia'],
            ['codigo' => 'JP', 'nome' => 'Japão'],
            ['codigo' => 'KE', 'nome' => 'Quênia'],
            ['codigo' => 'KG', 'nome' => 'Quirguiz, República da'],
            ['codigo' => 'KH', 'nome' => 'Camboja'],
            ['codigo' => 'KI', 'nome' => 'Kiribati'],
            ['codigo' => 'KM', 'nome' => 'Comores, Ilhas'],
            ['codigo' => 'KN', 'nome' => 'São Cristóvão e Neves, Ilhas'],
            ['codigo' => 'KP', 'nome' => 'Coréia (do Norte), Rep. Pop. Democrática da'],
            ['codigo' => 'KR', 'nome' => 'Coréia (do Sul), República da'],
            ['codigo' => 'KW', 'nome' => 'Kuwait'],
            ['codigo' => 'KY', 'nome' => 'Cayman, Ilhas'],
            ['codigo' => 'KZ', 'nome' => 'Cazaquistão, República do'],
            ['codigo' => 'LA', 'nome' => 'Laos, Rep. Pop. Democrática do'],
            ['codigo' => 'LB', 'nome' => 'Líbano'],
            ['codigo' => 'LC', 'nome' => 'Santa Lúcia'],
            ['codigo' => 'LI', 'nome' => 'Liechtenstein'],
            ['codigo' => 'LK', 'nome' => 'Sri Lanka'],
            ['codigo' => 'LR', 'nome' => 'Libéria'],
            ['codigo' => 'LS', 'nome' => 'Lesoto'],
            ['codigo' => 'LT', 'nome' => 'Lituânia, República da'],
            ['codigo' => 'LU', 'nome' => 'Luxemburgo'],
            ['codigo' => 'LV', 'nome' => 'Letônia, República da'],
            ['codigo' => 'LY', 'nome' => 'Líbia'],
            ['codigo' => 'MA', 'nome' => 'Marrocos'],
            ['codigo' => 'MC', 'nome' => 'Mônaco'],
            ['codigo' => 'MD', 'nome' => 'Moldávia, República da'],
            ['codigo' => 'ME', 'nome' => 'Montenegro'],
            ['codigo' => 'MF', 'nome' => 'São Martinho (Parte Francesa)'],
            ['codigo' => 'MG', 'nome' => 'Madagascar'],
            ['codigo' => 'MH', 'nome' => 'Marshall, Ilhas'],
            ['codigo' => 'MK', 'nome' => 'Macedônia, Ant. Rep. Iugoslava'],
            ['codigo' => 'ML', 'nome' => 'Mali'],
            ['codigo' => 'MM', 'nome' => 'Myanmar (Birmânia)'],
            ['codigo' => 'MN', 'nome' => 'Mongólia'],
            ['codigo' => 'MO', 'nome' => 'Macau'],
            ['codigo' => 'MP', 'nome' => 'Marianas do Norte'],
            ['codigo' => 'MQ', 'nome' => 'Martinica'],
            ['codigo' => 'MR', 'nome' => 'Mauritânia'],
            ['codigo' => 'MS', 'nome' => 'Montserrat, Ilhas'],
            ['codigo' => 'MT', 'nome' => 'Malta'],
            ['codigo' => 'MU', 'nome' => 'Maurício'],
            ['codigo' => 'MV', 'nome' => 'Maldivas'],
            ['codigo' => 'MW', 'nome' => 'Malavi'],
            ['codigo' => 'MX', 'nome' => 'México'],
            ['codigo' => 'MY', 'nome' => 'Malásia'],
            ['codigo' => 'MZ', 'nome' => 'Moçambique'],
            ['codigo' => 'NA', 'nome' => 'Namíbia'],
            ['codigo' => 'NC', 'nome' => 'Nova Caledônia'],
            ['codigo' => 'NE', 'nome' => 'Níger'],
            ['codigo' => 'NF', 'nome' => 'Norfolk, Ilha'],
            ['codigo' => 'NG', 'nome' => 'Nigéria'],
            ['codigo' => 'NI', 'nome' => 'Nicarágua'],
            ['codigo' => 'NL', 'nome' => 'Países Baixos (Holanda)'],
            ['codigo' => 'NO', 'nome' => 'Noruega'],
            ['codigo' => 'NP', 'nome' => 'Nepal'],
            ['codigo' => 'NR', 'nome' => 'Nauru'],
            ['codigo' => 'NU', 'nome' => 'Niue, Ilha'],
            ['codigo' => 'NZ', 'nome' => 'Nova Zelândia'],
            ['codigo' => 'OM', 'nome' => 'Omã'],
            ['codigo' => 'PA', 'nome' => 'Panamá'],
            ['codigo' => 'PE', 'nome' => 'Peru'],
            ['codigo' => 'PF', 'nome' => 'Polinésia Francesa'],
            ['codigo' => 'PG', 'nome' => 'Papua Nova Guiné'],
            ['codigo' => 'PH', 'nome' => 'Filipinas'],
            ['codigo' => 'PK', 'nome' => 'Paquistão'],
            ['codigo' => 'PL', 'nome' => 'Polônia, República da'],
            ['codigo' => 'PM', 'nome' => 'São Pedro e Miquelon'],
            ['codigo' => 'PN', 'nome' => 'Pitcairn, Ilha De'],
            ['codigo' => 'PR', 'nome' => 'Porto Rico'],
            ['codigo' => 'PS', 'nome' => 'Palestina'],
            ['codigo' => 'PT', 'nome' => 'Portugal'],
            ['codigo' => 'PW', 'nome' => 'Palau'],
            ['codigo' => 'PY', 'nome' => 'Paraguai'],
            ['codigo' => 'QA', 'nome' => 'Catar'],
            ['codigo' => 'RE', 'nome' => 'Reunião, Ilha'],
            ['codigo' => 'RO', 'nome' => 'Romênia'],
            ['codigo' => 'RS', 'nome' => 'Servia'],
            ['codigo' => 'RU', 'nome' => 'Rússia, Federação da'],
            ['codigo' => 'RW', 'nome' => 'Ruanda'],
            ['codigo' => 'SA', 'nome' => 'Arábia Saudita'],
            ['codigo' => 'SB', 'nome' => 'Salomão, Ilhas'],
            ['codigo' => 'SC', 'nome' => 'Seychelles'],
            ['codigo' => 'SD', 'nome' => 'Sudão'],
            ['codigo' => 'SE', 'nome' => 'Suécia'],
            ['codigo' => 'SG', 'nome' => 'Cingapura'],
            ['codigo' => 'SH', 'nome' => 'Santa Helena'],
            ['codigo' => 'SI', 'nome' => 'Eslovênia, República da'],
            ['codigo' => 'SJ', 'nome' => 'Svalbard e Jan Mayen'],
            ['codigo' => 'SK', 'nome' => 'Eslovaca, República'],
            ['codigo' => 'SL', 'nome' => 'Serra Leoa'],
            ['codigo' => 'SM', 'nome' => 'San Marino'],
            ['codigo' => 'SN', 'nome' => 'Senegal'],
            ['codigo' => 'SO', 'nome' => 'Somália'],
            ['codigo' => 'SR', 'nome' => 'Suriname'],
            ['codigo' => 'SS', 'nome' => 'Sudão do Sul'],
            ['codigo' => 'ST', 'nome' => 'São Tomé e Príncipe, Ilhas'],
            ['codigo' => 'SV', 'nome' => 'El Salvador'],
            ['codigo' => 'SX', 'nome' => 'São Martinho (Parte Holandesa)'],
            ['codigo' => 'SY', 'nome' => 'Síria, República Árabe da'],
            ['codigo' => 'SZ', 'nome' => 'Suazilândia'],
            ['codigo' => 'TC', 'nome' => 'Turcas e Caicos, Ilhas'],
            ['codigo' => 'TD', 'nome' => 'Chade'],
            ['codigo' => 'TF', 'nome' => 'Terras Austrais e Antárticas Francesas'],
            ['codigo' => 'TG', 'nome' => 'Togo'],
            ['codigo' => 'TH', 'nome' => 'Tailândia'],
            ['codigo' => 'TJ', 'nome' => 'Tadjiquistão, República do'],
            ['codigo' => 'TK', 'nome' => 'Toquelau, Ilhas'],
            ['codigo' => 'TL', 'nome' => 'Timor Leste'],
            ['codigo' => 'TM', 'nome' => 'Turcomenistão, República do'],
            ['codigo' => 'TN', 'nome' => 'Tunísia'],
            ['codigo' => 'TO', 'nome' => 'Tonga'],
            ['codigo' => 'TR', 'nome' => 'Turquia'],
            ['codigo' => 'TT', 'nome' => 'Trinidad e Tobago'],
            ['codigo' => 'TV', 'nome' => 'Tuvalu'],
            ['codigo' => 'TW', 'nome' => 'Formosa (Taiwan)'],
            ['codigo' => 'TZ', 'nome' => 'Tanzânia, Rep. Unida da'],
            ['codigo' => 'UA', 'nome' => 'Ucrânia'],
            ['codigo' => 'UG', 'nome' => 'Uganda'],
            ['codigo' => 'UM', 'nome' => 'Pacífico, Ilhas do (Possessão dos EUA)'],
            ['codigo' => 'US', 'nome' => 'Estados Unidos'],
            ['codigo' => 'UY', 'nome' => 'Uruguai'],
            ['codigo' => 'UZ', 'nome' => 'Uzbequistão, República do'],
            ['codigo' => 'VA', 'nome' => 'Vaticano, Est. da Cidade do'],
            ['codigo' => 'VC', 'nome' => 'São Vicente e Granadinas'],
            ['codigo' => 'VE', 'nome' => 'Venezuela'],
            ['codigo' => 'VG', 'nome' => 'Virgens, Ilhas (Britânicas)'],
            ['codigo' => 'VI', 'nome' => 'Virgens, Ilhas (E.U.A.)'],
            ['codigo' => 'VN', 'nome' => 'Vietnã'],
            ['codigo' => 'VU', 'nome' => 'Vanuatu'],
            ['codigo' => 'WF', 'nome' => 'Wallis e Futuna, Ilhas'],
            ['codigo' => 'WS', 'nome' => 'Samoa'],
            ['codigo' => 'YE', 'nome' => 'Iêmen'],
            ['codigo' => 'YT', 'nome' => 'Mayotte'],
            ['codigo' => 'ZA', 'nome' => 'África do Sul'],
            ['codigo' => 'ZM', 'nome' => 'Zâmbia'],
            ['codigo' => 'ZW', 'nome' => 'Zimbábue'],
            ['codigo' => 'ZZ', 'nome' => 'Município não possui a informação no sistema próprio;'],
        ];

        DB::table('paises')->upsert(
            $paises,
            ['codigo'],
            ['nome']
        );
    }
}
